'use client'

import { createContext, useContext, useEffect, useState } from 'react'

export type Language = 'en' | 'id'
const translations: Record<Language, Record<string, string>> = {
  en: { appName: 'Cloud NL', privateCloud: 'NasLabs private cloud', user: 'User', admin: 'Admin', myDrive: 'My Drive', favorites: 'Favorites', storageCleanup: 'Storage cleanup', trash: 'Trash', profile: 'Profile', settings: 'Settings', shared: 'Shared files', dashboard: 'Dashboard', users: 'Users', globalFiles: 'Global files', logs: 'Activity Logs', systemSettings: 'System settings', storage: 'Storage', search: 'Search files and folders...', notifications: 'Notifications', caughtUp: "You're all caught up.", signOut: 'Sign out', language: 'Language', languageDescription: 'Choose the language used across Cloud NL.', english: 'English', indonesian: 'Bahasa Indonesia', languageSaved: 'Language updated', markAllRead: 'Mark all read', unread: 'unread', tryAgain: 'Try again', retrying: 'Retrying...', noActivity: 'No activity logs found', recentActivity: 'Recent Activity', fileDistribution: 'File distribution', systemStorage: 'System Storage', topUsers: 'Top Users by Storage', uploaded: 'Uploaded', downloaded: 'Downloaded', movedToTrash: 'Moved to Trash', restored: 'Restored', renamed: 'Renamed', moved: 'Moved', createdFolder: 'Created Folder', updatedSetting: 'Updated Setting', updatedSettings: 'Updated Settings', upload: 'Upload', uploadFile: 'Upload files', uploadFolder: 'Upload folder', newFolder: 'New Folder', createFolder: 'Create folder', sort: 'Sort', filter: 'Filter', allItems: 'All items', favoritesOnly: 'Favorites only', foldersOnly: 'Folders only', filesOnly: 'Files only', images: 'Images', documents: 'Documents', videos: 'Videos', name: 'Name', type: 'Type', lastModified: 'Last modified', fileSize: 'File size', folders: 'Folders', files: 'Files', noFiles: 'No files yet', noResults: 'No results found', noResultsFor: 'No results for', searchDifferent: 'Try searching with a different keyword.', driveEmpty: 'Your drive is empty', driveEmptyDescription: 'Upload files or create folders to get started. Drag & drop files anywhere on this page.', folderEmpty: 'This folder is empty', folderEmptyDescription: 'Upload files or create a subfolder inside this folder.', trashEmpty: 'Trash is empty', trashEmptyDescription: 'Files and folders you delete will appear here.', profilePhoto: 'Profile photo', changePhoto: 'Change photo', remove: 'Remove', saveProfile: 'Save profile', securityPassword: 'Security & Password', updatePassword: 'Update password', driveStatus: 'Drive status', readyToStore: 'Ready to store files', cancel: 'Cancel', close: 'Close', save: 'Save', delete: 'Delete', rename: 'Rename', move: 'Move', download: 'Download', share: 'Share', fileInfo: 'File info', versionHistory: 'Version history', preview: 'Preview', restoreVersion: 'Restore version', loading: 'Loading...' },
  id: { appName: 'Cloud NL', privateCloud: 'Cloud privat NasLabs', user: 'Pengguna', admin: 'Admin', myDrive: 'Drive Saya', favorites: 'Favorit', storageCleanup: 'Bersihkan penyimpanan', trash: 'Sampah', profile: 'Profil', settings: 'Pengaturan', shared: 'File Dibagikan', dashboard: 'Dasbor', users: 'Pengguna', globalFiles: 'Semua file', logs: 'Log Aktivitas', systemSettings: 'Pengaturan sistem', storage: 'Penyimpanan', search: 'Cari file dan folder...', notifications: 'Notifikasi', caughtUp: 'Tidak ada notifikasi baru.', signOut: 'Keluar', language: 'Bahasa', languageDescription: 'Pilih bahasa yang digunakan di seluruh Cloud NL.', english: 'English', indonesian: 'Bahasa Indonesia', languageSaved: 'Bahasa diperbarui', markAllRead: 'Tandai semua dibaca', unread: 'belum dibaca', tryAgain: 'Coba lagi', retrying: 'Mencoba lagi...', noActivity: 'Belum ada log aktivitas', recentActivity: 'Aktivitas Terbaru', fileDistribution: 'Distribusi file', systemStorage: 'Penyimpanan Sistem', topUsers: 'Pengguna Teratas berdasarkan Penyimpanan', uploaded: 'Diunggah', downloaded: 'Diunduh', movedToTrash: 'Dipindahkan ke Sampah', restored: 'Dipulihkan', renamed: 'Diubah nama', moved: 'Dipindahkan', createdFolder: 'Folder Dibuat', updatedSetting: 'Pengaturan Diperbarui', updatedSettings: 'Pengaturan Diperbarui', upload: 'Unggah', uploadFile: 'Unggah file', uploadFolder: 'Unggah folder', newFolder: 'Folder Baru', createFolder: 'Buat folder', sort: 'Urutkan', filter: 'Filter', allItems: 'Semua item', favoritesOnly: 'Favorit saja', foldersOnly: 'Folder saja', filesOnly: 'File saja', images: 'Gambar', documents: 'Dokumen', videos: 'Video', name: 'Nama', type: 'Jenis', lastModified: 'Terakhir diubah', fileSize: 'Ukuran file', folders: 'Folder', files: 'File', noFiles: 'Belum ada file', noResults: 'Hasil tidak ditemukan', noResultsFor: 'Tidak ada hasil untuk', searchDifferent: 'Coba gunakan kata kunci lain.', driveEmpty: 'Drive Anda masih kosong', driveEmptyDescription: 'Unggah file atau buat folder untuk memulai. Anda juga dapat menarik file ke halaman ini.', folderEmpty: 'Folder ini masih kosong', folderEmptyDescription: 'Unggah file atau buat subfolder di dalam folder ini.', trashEmpty: 'Sampah masih kosong', trashEmptyDescription: 'File dan folder yang dihapus akan muncul di sini.', profilePhoto: 'Foto profil', changePhoto: 'Ganti foto', remove: 'Hapus', saveProfile: 'Simpan profil', securityPassword: 'Keamanan & Kata Sandi', updatePassword: 'Perbarui kata sandi', driveStatus: 'Status Drive', readyToStore: 'Siap menyimpan file', cancel: 'Batal', close: 'Tutup', save: 'Simpan', delete: 'Hapus', rename: 'Ubah nama', move: 'Pindahkan', download: 'Unduh', share: 'Bagikan', fileInfo: 'Info file', versionHistory: 'Riwayat versi', preview: 'Pratinjau', restoreVersion: 'Pulihkan versi', loading: 'Memuat...' },
}

const extraTranslations: Record<Language, Record<string, string>> = {
  en: { uploadDescription: 'Upload files or an entire folder to your current location.', dropFilesHere: 'Drag and drop files here', dropFilesDescription: 'You can upload one or multiple files. Drop a folder to upload its contents.', chooseFiles: 'Choose one or more files', chooseFolder: 'Choose a folder from your device', fileConflict: 'If a file already exists', replaceKeepHistory: 'Replace and keep version history', keepBoth: 'Keep both files', skipExisting: 'Skip existing files', customizeExperience: 'Customize your Cloud NL experience', preferencesDescription: 'Customize your Drive display options.', appearanceTheme: 'Appearance theme', appearanceDescription: 'Choose dark mode or system default theme', defaultDriveView: 'Default Drive view', defaultViewDescription: 'Default layout when navigating folder contents', dark: 'Dark', light: 'Light', system: 'System', gridView: 'Grid view', listView: 'List view', activeSessions: 'Active sessions', sessionsDescription: 'Manage devices currently signed in to your account.', sessionRevoked: 'Session revoked', allSessionsRevoked: 'All sessions revoked' },
  id: { uploadDescription: 'Unggah file atau seluruh folder ke lokasi saat ini.', dropFilesHere: 'Tarik dan letakkan file di sini', dropFilesDescription: 'Anda dapat mengunggah satu atau beberapa file. Letakkan folder untuk mengunggah isinya.', chooseFiles: 'Pilih satu atau beberapa file', chooseFolder: 'Pilih folder dari perangkat Anda', fileConflict: 'Jika file sudah ada', replaceKeepHistory: 'Ganti dan simpan riwayat versi', keepBoth: 'Simpan kedua file', skipExisting: 'Lewati file yang sudah ada', customizeExperience: 'Sesuaikan pengalaman Cloud NL', preferencesDescription: 'Sesuaikan tampilan Drive Anda.', appearanceTheme: 'Tema tampilan', appearanceDescription: 'Pilih mode gelap atau tema sistem', defaultDriveView: 'Tampilan Drive default', defaultViewDescription: 'Tata letak default saat membuka isi folder', dark: 'Gelap', light: 'Terang', system: 'Sistem', gridView: 'Tampilan grid', listView: 'Tampilan daftar', activeSessions: 'Sesi aktif', sessionsDescription: 'Kelola perangkat yang sedang masuk ke akun Anda.', sessionRevoked: 'Sesi dicabut', allSessionsRevoked: 'Semua sesi dicabut' },
}

const labels: Record<Language, Record<string, string>> = { en: { fullName: 'Full name', emailAddress: 'Email address', preferences: 'Preferences' }, id: { fullName: 'Nama lengkap', emailAddress: 'Alamat email', preferences: 'Preferensi' } }

const LanguageContext = createContext<{ language: Language; setLanguage: (language: Language) => void; t: (key: string) => string }>({ language: 'en', setLanguage: () => {}, t: key => key })

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')
  useEffect(() => {
    const saved = localStorage.getItem('drive_language')
    if (saved === 'id') {
      // Read browser preferences after the server/client HTML has matched.
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setLanguageState('id')
    }
    document.documentElement.lang = language
  }, [language])
  const setLanguage = (next: Language) => {
    setLanguageState(next)
    localStorage.setItem('drive_language', next)
    document.documentElement.lang = next
  }
  return <LanguageContext.Provider value={{ language, setLanguage, t: key => translations[language][key] ?? extraTranslations[language][key] ?? labels[language][key] ?? key }}>{children}</LanguageContext.Provider>
}

export function useLanguage() { return useContext(LanguageContext) }
