'use client'

import { useState } from 'react'
import { Copy, Link2, Loader2, Share2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { DriveFolder } from '@/types/drive'
import { createFolderShare } from '@/services/drive-api'
import { getApiErrorMessage } from '@/lib/api-client'
import { toast } from 'sonner'

export function FolderShareDialog({ folder, open, onOpenChange }: { folder: DriveFolder | null; open: boolean; onOpenChange: (open: boolean) => void }) {
  const [password, setPassword] = useState(''); const [expiresAt, setExpiresAt] = useState(''); const [permission, setPermission] = useState<'viewer' | 'editor'>('viewer'); const [shareUrl, setShareUrl] = useState(''); const [loading, setLoading] = useState(false)
  const reset = () => { setPassword(''); setExpiresAt(''); setPermission('viewer'); setShareUrl('') }
  const close = (next: boolean) => { if (!next) reset(); onOpenChange(next) }
  const create = async () => { if (!folder) return; setLoading(true); try { const share = await createFolderShare(folder.uuid, { permission, ...(password ? { password } : {}), ...(expiresAt ? { expires_at: new Date(`${expiresAt}T23:59:59`).toISOString() } : {}) }); const url = `${window.location.origin}/folder-share/${share.token}`; setShareUrl(url); await navigator.clipboard.writeText(url); toast.success('Folder share link created and copied') } catch (e: unknown) { toast.error(getApiErrorMessage(e, 'Unable to create folder share link')) } finally { setLoading(false) } }
  return <Dialog open={open} onOpenChange={close}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle className="flex items-center gap-2"><Share2 className="w-4 h-4 text-primary" /> Share folder</DialogTitle><DialogDescription className="truncate">Create a secure link for {folder?.name}</DialogDescription></DialogHeader>{shareUrl ? <div className="space-y-3 py-2"><div className="flex items-center gap-2 rounded-xl border border-border bg-secondary/50 p-3"><Link2 className="w-4 h-4 text-primary shrink-0" /><span className="text-xs break-anywhere min-w-0 flex-1">{shareUrl}</span><Button size="icon-sm" variant="outline" onClick={() => navigator.clipboard.writeText(shareUrl)}><Copy className="w-4 h-4" /></Button></div><p className="text-xs text-muted-foreground">Anyone with this link can browse the folder. Permission: <b>{permission === 'editor' ? 'Editor' : 'Viewer'}</b>.</p><DialogFooter><Button onClick={() => close(false)}>Done</Button></DialogFooter></div> : <div className="space-y-4 py-2"><div className="space-y-1.5"><label className="text-xs font-medium text-muted-foreground">Permission</label><select className="h-10 w-full rounded-md border border-border bg-background px-3 text-sm" value={permission} onChange={e => setPermission(e.target.value as 'viewer' | 'editor')}><option value="viewer">Viewer — browse and download</option><option value="editor">Editor — shared editing access</option></select></div><div className="space-y-1.5"><label className="text-xs font-medium text-muted-foreground">Password (optional)</label><Input type="password" placeholder="Require a password" value={password} onChange={e => setPassword(e.target.value)} minLength={4} /></div><div className="space-y-1.5"><label className="text-xs font-medium text-muted-foreground">Expires on (optional)</label><Input type="date" value={expiresAt} onChange={e => setExpiresAt(e.target.value)} min={new Date().toISOString().slice(0, 10)} /></div><DialogFooter><Button variant="outline" onClick={() => close(false)}>Cancel</Button><Button onClick={create} disabled={loading || (password.length > 0 && password.length < 4)}>{loading ? <><Loader2 className="w-4 h-4 mr-2 animate-spin" />Creating...</> : <><Link2 className="w-4 h-4 mr-2" />Create link</>}</Button></DialogFooter></div>}</DialogContent></Dialog>
}
